// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/display/entity/display_entity.dart';
import 'data/model/program/entity/program_entity.dart';
import 'data/model/sculpture/entity/sculpture_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6598904457189344182),
    name: 'DisplayEntity',
    lastPropertyId: const obx_int.IdUid(20, 2830003741279689243),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1261951655537456339),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4953187496180601836),
        name: 'dspyEnddeYmd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3647720591480755301),
        name: 'dspyStateNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5270670184668707752),
        name: 'placeNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2899574818334682767),
        name: 'mnnstNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4546884686393897988),
        name: 'writerNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1458510660555595693),
        name: 'prdctNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6075331978502831666),
        name: 'timeCharstCn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6240806755649418137),
        name: 'viewingCharstCn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8946823799046903232),
        name: 'ebookUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1394259889160073090),
        name: 'ebookNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6260099880112057637),
        name: 'dspyImageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1486136407126924420),
        name: 'dspyImageNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7150468270554977165),
        name: 'dspyEngNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3033427097878471933),
        name: 'dspyEngCn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2725274931871867661),
        name: 'regMngrNo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 503732186227303751),
        name: 'pavlnCharstNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8815973789744329479),
        name: 'dspyNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 140771943080445964),
        name: 'dspyBgndeYmd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 2830003741279689243),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3301241342219723367),
    name: 'SculptureEntity',
    lastPropertyId: const obx_int.IdUid(13, 7561527051738708480),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2778466307051098826),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2701843866171684373),
        name: 'titleKoNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4540772380721652610),
        name: 'titleEnNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6571981839767290068),
        name: 'sclptrSz',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4468095829977707783),
        name: 'mtrqltNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8147677184972149608),
        name: 'artistKoNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8670416249006381901),
        name: 'artistEnNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 235489591891654167),
        name: 'nationNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3292198911560156424),
        name: 'purchasedYmd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6023257406673743695),
        name: 'locationNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5050471466424183263),
        name: 'prdctOriginNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 288262033189662413),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7561527051738708480),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1607431116888307244),
    name: 'ProgramEntity',
    lastPropertyId: const obx_int.IdUid(15, 3243609034041254270),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6795095514583084615),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8921627449860774063),
        name: 'clssEndYmd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6338106506090665871),
        name: 'simTextCn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4596560067154309222),
        name: 'letTxtCn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2778357745525497991),
        name: 'rowNum',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7809742761503213152),
        name: 'placeNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 835052101203027998),
        name: 'ttnAmt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3541191450817627790),
        name: 'clssMbrCdNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8653384724278865407),
        name: 'clssStYmd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2018364985582129372),
        name: 'rcvCCdNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4561786222217388950),
        name: 'itemUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4368541320835739126),
        name: 'clssCNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3254042627981522719),
        name: 'clssNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1388395947253430240),
        name: 'clssCCdNm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3243609034041254270),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1607431116888307244),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DisplayEntity: obx_int.EntityDefinition<DisplayEntity>(
      model: _entities[0],
      toOneRelations: (DisplayEntity object) => [],
      toManyRelations: (DisplayEntity object) => {},
      getId: (DisplayEntity object) => object.id,
      setId: (DisplayEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DisplayEntity object, fb.Builder fbb) {
        final dspyEnddeYmdOffset = fbb.writeString(object.dspyEnddeYmd);
        final dspyStateNmOffset = fbb.writeString(object.dspyStateNm);
        final placeNmOffset = fbb.writeString(object.placeNm);
        final mnnstNmOffset = fbb.writeString(object.mnnstNm);
        final writerNmOffset = fbb.writeString(object.writerNm);
        final prdctNmOffset = fbb.writeString(object.prdctNm);
        final timeCharstCnOffset = fbb.writeString(object.timeCharstCn);
        final viewingCharstCnOffset = fbb.writeString(object.viewingCharstCn);
        final ebookUrlOffset = fbb.writeString(object.ebookUrl);
        final ebookNmOffset = fbb.writeString(object.ebookNm);
        final dspyImageUrlOffset = fbb.writeString(object.dspyImageUrl);
        final dspyImageNmOffset = fbb.writeString(object.dspyImageNm);
        final dspyEngNmOffset = fbb.writeString(object.dspyEngNm);
        final dspyEngCnOffset = fbb.writeString(object.dspyEngCn);
        final regMngrNoOffset = fbb.writeString(object.regMngrNo);
        final pavlnCharstNmOffset = fbb.writeString(object.pavlnCharstNm);
        final dspyNmOffset = fbb.writeString(object.dspyNm);
        final dspyBgndeYmdOffset = fbb.writeString(object.dspyBgndeYmd);
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dspyEnddeYmdOffset);
        fbb.addOffset(2, dspyStateNmOffset);
        fbb.addOffset(3, placeNmOffset);
        fbb.addOffset(4, mnnstNmOffset);
        fbb.addOffset(5, writerNmOffset);
        fbb.addOffset(6, prdctNmOffset);
        fbb.addOffset(7, timeCharstCnOffset);
        fbb.addOffset(8, viewingCharstCnOffset);
        fbb.addOffset(9, ebookUrlOffset);
        fbb.addOffset(10, ebookNmOffset);
        fbb.addOffset(11, dspyImageUrlOffset);
        fbb.addOffset(12, dspyImageNmOffset);
        fbb.addOffset(13, dspyEngNmOffset);
        fbb.addOffset(14, dspyEngCnOffset);
        fbb.addOffset(15, regMngrNoOffset);
        fbb.addOffset(16, pavlnCharstNmOffset);
        fbb.addOffset(17, dspyNmOffset);
        fbb.addOffset(18, dspyBgndeYmdOffset);
        fbb.addInt64(19, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dspyEnddeYmdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dspyStateNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final placeNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final mnnstNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final writerNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final prdctNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final timeCharstCnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final viewingCharstCnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final ebookUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final ebookNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final dspyImageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final dspyImageNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final dspyEngNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final dspyEngCnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final regMngrNoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final pavlnCharstNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final dspyNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final dspyBgndeYmdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 42, 0),
        );
        final object = DisplayEntity(
          id: idParam,
          dspyEnddeYmd: dspyEnddeYmdParam,
          dspyStateNm: dspyStateNmParam,
          placeNm: placeNmParam,
          mnnstNm: mnnstNmParam,
          writerNm: writerNmParam,
          prdctNm: prdctNmParam,
          timeCharstCn: timeCharstCnParam,
          viewingCharstCn: viewingCharstCnParam,
          ebookUrl: ebookUrlParam,
          ebookNm: ebookNmParam,
          dspyImageUrl: dspyImageUrlParam,
          dspyImageNm: dspyImageNmParam,
          dspyEngNm: dspyEngNmParam,
          dspyEngCn: dspyEngCnParam,
          regMngrNo: regMngrNoParam,
          pavlnCharstNm: pavlnCharstNmParam,
          dspyNm: dspyNmParam,
          dspyBgndeYmd: dspyBgndeYmdParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    SculptureEntity: obx_int.EntityDefinition<SculptureEntity>(
      model: _entities[1],
      toOneRelations: (SculptureEntity object) => [],
      toManyRelations: (SculptureEntity object) => {},
      getId: (SculptureEntity object) => object.id,
      setId: (SculptureEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SculptureEntity object, fb.Builder fbb) {
        final titleKoNmOffset = fbb.writeString(object.titleKoNm);
        final titleEnNmOffset = fbb.writeString(object.titleEnNm);
        final sclptrSzOffset = fbb.writeString(object.sclptrSz);
        final mtrqltNmOffset = fbb.writeString(object.mtrqltNm);
        final artistKoNmOffset = fbb.writeString(object.artistKoNm);
        final artistEnNmOffset = fbb.writeString(object.artistEnNm);
        final nationNmOffset = fbb.writeString(object.nationNm);
        final purchasedYmdOffset = fbb.writeString(object.purchasedYmd);
        final locationNmOffset = fbb.writeString(object.locationNm);
        final prdctOriginNmOffset = fbb.writeString(object.prdctOriginNm);
        final imageUrlOffset = fbb.writeString(object.imageUrl);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleKoNmOffset);
        fbb.addOffset(2, titleEnNmOffset);
        fbb.addOffset(3, sclptrSzOffset);
        fbb.addOffset(4, mtrqltNmOffset);
        fbb.addOffset(5, artistKoNmOffset);
        fbb.addOffset(6, artistEnNmOffset);
        fbb.addOffset(7, nationNmOffset);
        fbb.addOffset(8, purchasedYmdOffset);
        fbb.addOffset(9, locationNmOffset);
        fbb.addOffset(10, prdctOriginNmOffset);
        fbb.addOffset(11, imageUrlOffset);
        fbb.addInt64(12, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleKoNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleEnNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sclptrSzParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final mtrqltNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final artistKoNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final artistEnNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final nationNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final purchasedYmdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final locationNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final prdctOriginNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final object = SculptureEntity(
          id: idParam,
          titleKoNm: titleKoNmParam,
          titleEnNm: titleEnNmParam,
          sclptrSz: sclptrSzParam,
          mtrqltNm: mtrqltNmParam,
          artistKoNm: artistKoNmParam,
          artistEnNm: artistEnNmParam,
          nationNm: nationNmParam,
          purchasedYmd: purchasedYmdParam,
          locationNm: locationNmParam,
          prdctOriginNm: prdctOriginNmParam,
          imageUrl: imageUrlParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    ProgramEntity: obx_int.EntityDefinition<ProgramEntity>(
      model: _entities[2],
      toOneRelations: (ProgramEntity object) => [],
      toManyRelations: (ProgramEntity object) => {},
      getId: (ProgramEntity object) => object.id,
      setId: (ProgramEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProgramEntity object, fb.Builder fbb) {
        final clssEndYmdOffset = fbb.writeString(object.clssEndYmd);
        final simTextCnOffset = fbb.writeString(object.simTextCn);
        final letTxtCnOffset = fbb.writeString(object.letTxtCn);
        final rowNumOffset = fbb.writeString(object.rowNum);
        final placeNmOffset = fbb.writeString(object.placeNm);
        final ttnAmtOffset = fbb.writeString(object.ttnAmt);
        final clssMbrCdNmOffset = fbb.writeString(object.clssMbrCdNm);
        final clssStYmdOffset = fbb.writeString(object.clssStYmd);
        final rcvCCdNmOffset = fbb.writeString(object.rcvCCdNm);
        final itemUrlOffset = fbb.writeString(object.itemUrl);
        final clssCNmOffset = fbb.writeString(object.clssCNm);
        final clssNmOffset = fbb.writeString(object.clssNm);
        final clssCCdNmOffset = fbb.writeString(object.clssCCdNm);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, clssEndYmdOffset);
        fbb.addOffset(2, simTextCnOffset);
        fbb.addOffset(3, letTxtCnOffset);
        fbb.addOffset(4, rowNumOffset);
        fbb.addOffset(5, placeNmOffset);
        fbb.addOffset(6, ttnAmtOffset);
        fbb.addOffset(7, clssMbrCdNmOffset);
        fbb.addOffset(8, clssStYmdOffset);
        fbb.addOffset(9, rcvCCdNmOffset);
        fbb.addOffset(10, itemUrlOffset);
        fbb.addOffset(11, clssCNmOffset);
        fbb.addOffset(12, clssNmOffset);
        fbb.addOffset(13, clssCCdNmOffset);
        fbb.addInt64(14, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final clssEndYmdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final simTextCnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final letTxtCnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final rowNumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final placeNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final ttnAmtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final clssMbrCdNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final clssStYmdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final rcvCCdNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final itemUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final clssCNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final clssNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final clssCCdNmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0),
        );
        final object = ProgramEntity(
          id: idParam,
          clssEndYmd: clssEndYmdParam,
          simTextCn: simTextCnParam,
          letTxtCn: letTxtCnParam,
          rowNum: rowNumParam,
          placeNm: placeNmParam,
          ttnAmt: ttnAmtParam,
          clssMbrCdNm: clssMbrCdNmParam,
          clssStYmd: clssStYmdParam,
          rcvCCdNm: rcvCCdNmParam,
          itemUrl: itemUrlParam,
          clssCNm: clssCNmParam,
          clssNm: clssNmParam,
          clssCCdNm: clssCCdNmParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DisplayEntity] entity fields to define ObjectBox queries.
class DisplayEntity_ {
  /// See [DisplayEntity.id].
  static final id = obx.QueryIntegerProperty<DisplayEntity>(
    _entities[0].properties[0],
  );

  /// See [DisplayEntity.dspyEnddeYmd].
  static final dspyEnddeYmd = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[1],
  );

  /// See [DisplayEntity.dspyStateNm].
  static final dspyStateNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[2],
  );

  /// See [DisplayEntity.placeNm].
  static final placeNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[3],
  );

  /// See [DisplayEntity.mnnstNm].
  static final mnnstNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[4],
  );

  /// See [DisplayEntity.writerNm].
  static final writerNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[5],
  );

  /// See [DisplayEntity.prdctNm].
  static final prdctNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[6],
  );

  /// See [DisplayEntity.timeCharstCn].
  static final timeCharstCn = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[7],
  );

  /// See [DisplayEntity.viewingCharstCn].
  static final viewingCharstCn = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[8],
  );

  /// See [DisplayEntity.ebookUrl].
  static final ebookUrl = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[9],
  );

  /// See [DisplayEntity.ebookNm].
  static final ebookNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[10],
  );

  /// See [DisplayEntity.dspyImageUrl].
  static final dspyImageUrl = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[11],
  );

  /// See [DisplayEntity.dspyImageNm].
  static final dspyImageNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[12],
  );

  /// See [DisplayEntity.dspyEngNm].
  static final dspyEngNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[13],
  );

  /// See [DisplayEntity.dspyEngCn].
  static final dspyEngCn = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[14],
  );

  /// See [DisplayEntity.regMngrNo].
  static final regMngrNo = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[15],
  );

  /// See [DisplayEntity.pavlnCharstNm].
  static final pavlnCharstNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[16],
  );

  /// See [DisplayEntity.dspyNm].
  static final dspyNm = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[17],
  );

  /// See [DisplayEntity.dspyBgndeYmd].
  static final dspyBgndeYmd = obx.QueryStringProperty<DisplayEntity>(
    _entities[0].properties[18],
  );

  /// See [DisplayEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<DisplayEntity>(
    _entities[0].properties[19],
  );
}

/// [SculptureEntity] entity fields to define ObjectBox queries.
class SculptureEntity_ {
  /// See [SculptureEntity.id].
  static final id = obx.QueryIntegerProperty<SculptureEntity>(
    _entities[1].properties[0],
  );

  /// See [SculptureEntity.titleKoNm].
  static final titleKoNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[1],
  );

  /// See [SculptureEntity.titleEnNm].
  static final titleEnNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[2],
  );

  /// See [SculptureEntity.sclptrSz].
  static final sclptrSz = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[3],
  );

  /// See [SculptureEntity.mtrqltNm].
  static final mtrqltNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[4],
  );

  /// See [SculptureEntity.artistKoNm].
  static final artistKoNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[5],
  );

  /// See [SculptureEntity.artistEnNm].
  static final artistEnNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[6],
  );

  /// See [SculptureEntity.nationNm].
  static final nationNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[7],
  );

  /// See [SculptureEntity.purchasedYmd].
  static final purchasedYmd = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[8],
  );

  /// See [SculptureEntity.locationNm].
  static final locationNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[9],
  );

  /// See [SculptureEntity.prdctOriginNm].
  static final prdctOriginNm = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[10],
  );

  /// See [SculptureEntity.imageUrl].
  static final imageUrl = obx.QueryStringProperty<SculptureEntity>(
    _entities[1].properties[11],
  );

  /// See [SculptureEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<SculptureEntity>(
    _entities[1].properties[12],
  );
}

/// [ProgramEntity] entity fields to define ObjectBox queries.
class ProgramEntity_ {
  /// See [ProgramEntity.id].
  static final id = obx.QueryIntegerProperty<ProgramEntity>(
    _entities[2].properties[0],
  );

  /// See [ProgramEntity.clssEndYmd].
  static final clssEndYmd = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[1],
  );

  /// See [ProgramEntity.simTextCn].
  static final simTextCn = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[2],
  );

  /// See [ProgramEntity.letTxtCn].
  static final letTxtCn = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[3],
  );

  /// See [ProgramEntity.rowNum].
  static final rowNum = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[4],
  );

  /// See [ProgramEntity.placeNm].
  static final placeNm = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[5],
  );

  /// See [ProgramEntity.ttnAmt].
  static final ttnAmt = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[6],
  );

  /// See [ProgramEntity.clssMbrCdNm].
  static final clssMbrCdNm = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[7],
  );

  /// See [ProgramEntity.clssStYmd].
  static final clssStYmd = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[8],
  );

  /// See [ProgramEntity.rcvCCdNm].
  static final rcvCCdNm = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[9],
  );

  /// See [ProgramEntity.itemUrl].
  static final itemUrl = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[10],
  );

  /// See [ProgramEntity.clssCNm].
  static final clssCNm = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[11],
  );

  /// See [ProgramEntity.clssNm].
  static final clssNm = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[12],
  );

  /// See [ProgramEntity.clssCCdNm].
  static final clssCCdNm = obx.QueryStringProperty<ProgramEntity>(
    _entities[2].properties[13],
  );

  /// See [ProgramEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ProgramEntity>(
    _entities[2].properties[14],
  );
}
